#ifndef CONFIG_H
#define CONFIG_H

#define SERIAL_BAUD_RATE 115200

#define SCREEN_WIDTH 128
#define SCREEN_HEIGHT 64
#define OLED_ADDRESS_PRIMARY 0x3C
#define OLED_ADDRESS_SECONDARY 0x3D

#define OLED_SDA_PIN 8
#define OLED_SCL_PIN 9
#define OLED_DC_PIN 18
#define OLED_RESET_PIN -1

#define FEED_BUTTON_PIN 10
#define DIAPER_BUTTON_PIN 11
#define MENU_BUTTON_PIN 12
#define SELECT_BUTTON_PIN 13

#define BUTTON_COUNT 4
#define BUTTON_EVENT_QUEUE_SIZE 5
#define BUTTON_DEBOUNCE_MS 35

#define SPLASH_DURATION_MS 2200
#define STATUS_DURATION_MS 1400
#define SCREEN_REFRESH_MS 250
#define SLEEP_TIMEOUT_MS 60000UL

#endif
