#ifndef CONFIG_H
#define CONFIG_H

#define SERIAL_BAUD_RATE 115200

#define SCREEN_WIDTH 128
#define SCREEN_HEIGHT 64
#define OLED_ADDRESS 0x3C

#define OLED_SDA_PIN 8
#define OLED_SCL_PIN 9
#define OLED_DC_PIN 18
#define OLED_RESET_PIN 35

// 2x2 Keypad Matrix Pins
#define KEYPAD_ROW0_PIN 10
#define KEYPAD_ROW1_PIN 11
#define KEYPAD_COL0_PIN 12
#define KEYPAD_COL1_PIN 13

#define KEYPAD_ROWS 2
#define KEYPAD_COLS 2
#define BUTTON_COUNT 4
#define BUTTON_EVENT_QUEUE_SIZE 5
#define BUTTON_DEBOUNCE_MS 35

#define SPLASH_DURATION_MS 2200
#define STATUS_DURATION_MS 1400
#define SCREEN_REFRESH_MS 250
#define SLEEP_TIMEOUT_MS 60000UL

#endif
